export {default as AboutSection} from  './About'
export {default as ContactSection} from  './Contact'
export {default as HomeSection} from  './Home'
export {default as PortfolioSection} from  './Portfolio'
export {default as ServicesSection} from  './Services'