export {default as AboutSection} from  './About'
export {default as ContactSection} from  './Contact'
export {default as HomeSection} from  './Home'
export {default as ProjectsSection} from  './Projects'
export {default as ServicesSection} from  './Services'